version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
